config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#landing"
  get "/dashboard", to: "pages#dashboard", as: "dashboard"

  resources :languages, only: %i[index show] do
    resources :tracks, only: %i[show]
  end

  resources :recordings, only: [:new, :create]

  resources :lessons, only: %i[index show create] do
    resources :posts, only: %i[index show create]
  end

  resources :posts, only: %i[destroy] do
    resources :comments, only: %i[create destroy]
  end

  resources :comments, only: %i[destroy]

  resources :prompts, only: %i[new create show] do
    collection do
      post :generate_text
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :content, presence: true
end

app/models/hint.rb
class Hint < ActiveRecord::Base
  belongs_to :lesson

  validates :content, presence: true
  validates :lesson_id, presence: true
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :tracks, dependent: :destroy
  has_one_attached :image

  validates :name, presence: true
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :track
  has_many :started_lessons,  dependent: :destroy
  has_many :hints, dependent: :destroy
  has_many :posts, dependent: :destroy

  validates :title, presence: true
  validates :content, presence: true
  validates :track_id, presence: true
  validates :difficulty, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :lesson
  has_many :comments, dependent: :destroy

  validates :content, presence: true
  validates :title, presence: true

  default_scope -> { order(created_at: :desc) }

  def self.from_users_followed_by(user)

    followed_user_ids = "SELECT followed_id FROM relationships
                          WHERE follower_id = :user_id"
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id",
          user_id: user.id)
  end
end

app/models/prompt.rb
class Prompt < ActiveRecord::Base
  belongs_to :user

  validates :question, presence: true
end

app/models/recording.rb
class Recording < ApplicationRecord
  belongs_to :user
  has_one_attached :audio
end

app/models/started_lesson.rb
class StartedLesson < ActiveRecord::Base
  belongs_to :lesson
  belongs_to :user

  validates :lesson_id, presence: true
  validates :user_id, presence: true
  validates :staus, presence: true
end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :language
  has_many :lessons, dependent: :destroy

  validates :title, presence: true
  validates :language, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :avatar
  has_many :recordings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: { message: 'This username is already in use' }
  validates :password, presence: true

  has_many :started_lessons, dependent: :destroy
  has_many :lessons, through: :started_lessons
  has_many :tracks, through: :lessons
  has_many :posts
  has_many :comments
  has_many :prompts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
        # For additional fields in app/views/devise/registrations/new.html.erb
        devise_parameter_sanitizer.permit(:sign_up, keys: %i[username avatar])

        # For additional in app/views/devise/registrations/edit.html.erb
        devise_parameter_sanitizer.permit(:account_update, keys: %i[username avatar])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[edit update destroy]

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @comment.post = @post
    if @comment.save
      flash[:notice] = "Comment created successfully."
      redirect_to lesson_post_path(@post.lesson.id, @post)
    else
      flash[:alert] = "Comments can't be empty."
    end
  end

  def destroy
    @comment.destroy
    redirect_to lesson_post_path(@comment.post.lesson, @comment.post), notice: "Comment successfully deleted."
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @language = Language.includes(:image_attachment)
    @languages = Language.all
  end

  def show
    @language = Language.find(params[:id])
    @tracks = @language.tracks
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show]

  def show
  end

  def search
    query = params[:query]
    @lessons = Lesson.where("title LIKE ? OR content LIKE ?", "%#{query}%", "%#{query}%")
  end

  private

  def set_lesson
    @lesson = Lesson.find(params[:id])
  end

  def lesson_params
    params.require(:lesson).permit(:title, :content, :columns_explanation, :difficulty)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[landing dashboard]
  layout 'landing', only: [:landing]
  

  def landing
  end

  def dashboard
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show destroy]
  before_action :set_lesson, only: %i[index create]

  def index
    @post = Post.new
  end

  def show
    @comment = Comment.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @post.lesson = @lesson
    if @post.save
      redirect_to lesson_posts_path(@lesson)
    else
      render :index, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy
    redirect_to lesson_path(@post.lesson.id), notice: "Post successfully deleted."
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def set_lesson
    @lesson = Lesson.find(params[:lesson_id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/prompts_controller.rb
class PromptsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[show new generate_text]

  def show
    @prompt = Prompt.find(params[:id])
  end

  def new 
    @prompt = Prompt.new
  end

  def generate_text
    @prompt = Prompt.new(prompt_params)
    @prompt.user = current_user

    response = OpenaiService.new("#{prompt_params[:question]} - dont give the answer, explain me what's wrong, short concise words").call
    @prompt.answer = response

    if @prompt.save
      redirect_to prompt_path(@prompt)
    else
      render json: @prompt.errors, status: :unprocessable_entity
    end
  end
  
  private

  def prompt_params
    params.require(:prompt).permit(:question)
  end
end

app/controllers/recordings_controller.rb
class RecordingsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[new create]

  def new
      @recording = Recording.new
      @recordings = Recording.all
    end
  
    def create
      @recording = Recording.new(recording_params)
      @recording.user = current_user
      
      if @recording.save
        redirect_to root_path
      else
        render :new, status: :unprocessable_entity
      end
    end
  
    private
  
    def recording_params
      params.require(:recording).permit(:audio)
    end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  # Do we want this still?
  skip_before_action :authenticate_user!, only: [:show]

  before_action :set_language, :set_track, only: [:show]

  def show
     @lessons = @track.lessons
  end

  private

  def set_language
    @language = Language.find(params[:language_id])
  end

  def set_track
    @track = @language.tracks.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/languages/index.html.erb
<div class="screen2">
  <ul class="icons2">
    <div class="d-flex justify-content-center">
      <div class="row">
        <% @languages.each do |language| %>
          <div class="col-md-6 col-lg-5 mb-4">
            <div class="d-flex flex-column align-items-center">
              <%= link_to image_tag("icons/#{language.name}.svg", size: '250x250', crop: :fill), language_path(language) %>
              <div class="align-self-center mb-2">
                <h1><%= language.name %></h1>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </ul>
</div>

app/views/languages/show.html.erb
<div class="d-flex justify-content-center align-items-center bg-white">
  <div class="lines"></div>
  <div class="title-wrapper px-4">
    <h1><%= @language.name %></h1>
  </div>
  <div class="lines"></div>
</div>
<div class="screen2">
  <ul class="icons2">
    <div class="d-flex flex-wrap justify-content-center">
      <% @tracks.each do |track| %>
        <div class="col-3 mb-4">
          <%= link_to language_track_path(@language, track), class: 'link-dark' do %>
            <div class="d-flex flex-column align-items-center">
              <div>
                <%= image_tag 'folder.svg' %>
              </div>
              <div class="folder-wrapper">
                <p><%= track.title %></p>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
      <div class="d-flex justify-content-center mt-4">
        <%= link_to languages_path, class: "mb-4 text-dark folder-wrapper" do %>
          <strong>↵Back to languages</strong>
        <% end %>
      </div>
    </div>
  </ul>
</div>

app/views/lessons/show.html.erb
<div class="d-flex justify-content-center align-items-center bg-white">
  <div class="lines"></div>
  <div class="title-wrapper px-4">
    <h1><%= @lesson.title %></h1>
  </div>
  <div class="lines"></div>
</div>
<div class="screen2">
  <ul class="icons2">
    <div class="mt-5 mx-5">
      <iframe height="400" style="width: 100%;" scrolling="no" title="[ NUTSHELL ] - ES6 Generators and Iterators" src="https://codepen.io/ppozniak95/embed/yXgoxp?default-tab=html%2Cresult&editable=true" frameborder="no" loading="lazy" allowtransparency="true" allowfullscreen="true">
        See the Pen <a href="https://codepen.io/ppozniak95/pen/yXgoxp">
          [ NUTSHELL ] - ES6 Generators and Iterators</a> by Patryk Poźniak (<a href="https://codepen.io/ppozniak95">@ppozniak95</a>)
        on <a href="https://codepen.io">CodePen</a>.
      </iframe>
    </div>
    <div class="d-flex justify-content-between mt-4">
      <div id="btn-margin">
        <%= link_to "Are you stuck? Ask the community!", lesson_posts_path(lesson_id: @lesson.id), class: "btn btn-primary" %>
      </div>
      <div class="back-btn-margin">
        <%= link_to language_track_path(@lesson.track.language, @lesson.track), class: "text-dark folder-wrapper p-2" do %>
          <strong>↵Back to lessons overview</strong>
        <% end %>
      </div>
      <div class="filler"></div>
    </div>
  </ul>
</div>

app/views/posts/index.html.erb
<div class="d-flex justify-content-center align-items-center bg-white">
  <div class="lines"></div>
  <div class="title-wrapper px-4">
    <h1 class="text-dark text-decoration-none">Community</h1>
  </div>
  <div class="lines"></div>
</div>

<div class="screen2">
  <ul class="icons2">
    <div class="d-flex justify-content-evenly">
      <div class="row row-cols-3" id="background-prompt">
        <% @lesson.posts.each do |post| %>
          <div class="col mx-5">
            <div class="community-window">
              <div class="bar">
                <i></i>
                <div>
                  <p><%= @lesson.title %></p>
                </div>
              </div>
              <div class="content">
                <%= link_to lesson_post_path(@lesson, post), class: "text-decoration-none" do %>
                  <h6 class="text-dark"><%= post.title %></h6>
                  <p class="text-dark"><%= post.content %></p>
                  <div class="d-flex flex-column justify-content-between">
                    <div class="negative-margin">
                      <p class="text-dark"><strong>Posted by:</strong> <%= post.user.username %></p>
                    </div>
                    <div>
                      <p class="text-secondary">
                        <% if post.created_at.to_date == Date.today %>
                          <%= "Today, #{post.created_at.strftime('%H:%M')}" %>
                        <% elsif post.created_at.to_date == Date.yesterday %>
                          <%= "Yesterday, #{post.created_at.strftime('%H:%M')}" %>
                        <% else %>
                          <%= post.created_at.strftime('%d-%m-%Y %H:%M') %>
                        <% end %>
                      </p>
                      <button class="btn btn-primary">Contribute</button>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div id="background-prompt">
        <div class="community-window">
          <div class="bar">
            <i></i>
            <div>
              <p><%= "Your question not here?" %></p>
            </div>
          </div>
          <div class="content">
            <h6>Create a new thread</h6>
            <%= simple_form_for [@lesson, @post] do |f| %>
              <%= f.input :title, as: :text, input_html: { rows: 1 }, label: "What is your question about?" %>
              <%= f.input :content, as: :text, input_html: { rows: 3 }, label: "Take some time to explain your question." %>
              <%= f.button :submit, class: 'btn btn-primary' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="d-flex justify-content-center">
      <%= link_to lesson_path(@lesson), class: "text-dark folder-wrapper" do %>
        <strong>↵Back to lesson</strong>
      <% end %>
    </div>
  </ul>
</div>

app/views/posts/show.html.erb
<div class="d-flex justify-content-center align-items-center bg-white">
  <div class="lines"></div>
  <div class="title-wrapper px-4">
    <h1 class="text-dark text-decoration-none">Community</h1>
  </div>
  <div class="lines"></div>
</div>
<div class="screen2">
  <ul class="icons2">
    <div class="d-flex justify-content-center align-items-center">
      <div id="background-prompt">
        <div class="community-window">
          <div class="bar">
            <i></i>
            <div>
              <p><%= @post.title %></p>
            </div>
          </div>
          <div>
            <div class="content">
              <div>
                <p id="content-text"><%= @post.content %></p>
                <p><strong>Posted by:</strong> <%= @post.user.username %></p>
                <div>
                  <p class="text-secondary">
                    <% if @post.created_at.present? %>
                      <% if @post.created_at.to_date == Date.today %>
                        <%= "Today, #{@post.created_at.strftime('%H:%M')}" %>
                      <% elsif @post.created_at.to_date == Date.yesterday %>
                        <%= "Yesterday, #{@post.created_at.strftime('%H:%M')}" %>
                      <% else %>
                        <%= @post.created_at.strftime('%d-%m-%Y %H:%M') %>
                      <% end %>
                    <% end %>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div id="background-prompt">
        <div class="community-window">
          <div class="bar">
            <i></i>
            <div>
              <p>Answers</p>
            </div>
          </div>
          <div>
            <% @post.comments.each do |comment| %>
              <div class="content">
                <div>
                  <p><%= comment.content %></p>
                  <p><strong>Posted by:</strong> <%= comment.user.username %></p>
                  <div>
                    <p class="text-secondary">
                      <% if comment.created_at.present? %>
                        <% if comment.created_at.to_date == Date.today %>
                          <%= "Today, #{comment.created_at.strftime('%H:%M')}" %>
                        <% elsif comment.created_at.to_date == Date.yesterday %>
                          <%= "Yesterday, #{comment.created_at.strftime('%H:%M')}" %>
                        <% else %>
                          <%= comment.created_at.strftime('%d-%m-%Y %H:%M') %>
                        <% end %>
                      <% end %>
                    </p>
                  </div>
                  <% if comment.user == current_user %>
                    <%= button_to "Delete", post_comment_path(@post, comment), method: :delete, remote: true, class: "btn-tertiary btn-ter-danger", data: { turbo_action: "remove" } %>
                  <% end %>
                  <hr>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div id="background-prompt">
        <div class="community-window">
          <div class="bar">
            <i></i>
            <div>
              <p>Your Answer</p>
            </div>
          </div>
          <div class="content">
            <%= simple_form_for [@post, @comment] do |f| %>
              <%= f.input :content, as: :text, input_html: { rows: 3 }, label: false %>
              <%= f.button :submit, class: 'btn btn-primary' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="d-flex justify-content-center">
      <%= link_to lesson_posts_path(@post.lesson), class: "text-dark folder-wrapper" do %>
        <strong>↵Back</strong>
      <% end %>
    </div>
  </ul>
</div>

app/views/prompts/create.html.erb
<h1>Prompts#create</h1>
<p>Find me in app/views/prompts/create.html.erb</p>

app/views/prompts/new.html.erb
<div class="d-flex justify-content-center align-items-center bg-white">
  <div class="lines"></div>
  <div class="title-wrapper px-4">
    <h1 class="text-dark text-decoration-none">Let's explain your bug</h1>
  </div>
  <div class="lines"></div>
</div>
<div class="screen2">
  <ul class="icons2">
    <div class="d-flex justify-content-evenly" id="background-prompt">
      <div class="window">
        <div class="bar">
          <i></i>
          <div>
            <p data-controller="hello">Tell me your bug</p>
          </div>
        </div>
        <div class="content" data-controller="prompts">
          <%= form_with(model: @prompt, url: generate_text_prompts_path, data: { target: "prompts.bugDescription" }) do |form| %>
            <%= form.text_area :question, id: "bug-description", class: "bug-textarea", placeholder: "Enter your bug description" %>
            <%= form.button :submit, class: "submit-button" %>
          <% end %>
        </div>
      </div>
      <div class="window">
        <div class="bar">
          <i></i>
          <div>
            <p>Explanation</p>
          </div>
        </div>
        <div class="content" data-controller="prompts">
          <%= simple_form_for @prompt, url: generate_text_prompts_path, html: { data: { target: 'prompts.bugDescription' } } do |form| %>
            <%= form.text_area :answer, id: 'bug-description', class: 'bug-textarea', placeholder: 'Wait for your explanation' %>
            <%# <%= form.button :submit, class: 'submit-button', 'data-action': 'click->prompts#generateText' %>
          <% end %>
        </div>
      </div>
    </div>
  </ul>
</div>

app/views/prompts/show.html.erb
<div class="d-flex justify-content-evenly align-items-center bg-white">
  <div class="lines"></div>
  <div class="title-wrapper px-4">
    <h1 class="lang-title2">Read carefully</h1>
  </div>
  <div class="lines"></div>
</div>
<div>
  <div class="screen2">
    <ul class="icons2">
      <div class="d-flex justify-content-evenly" id="background-prompt">
        <div class="window">
          <div class="bar">
            <i></i>
            <div>
              <p data-controller="hello" >Tell me your bug</p>
            </div>
          </div>
          <div class="content" data-controller="prompts">
            <%= form_with(model: @prompt, url: generate_text_prompts_path, method: :post, data: { target: "prompts.bugDescription" }) do |form| %>
              <%= form.text_area :question, id: "bug-description", class: "bug-textarea", placeholder: "Enter your bug description" %>
              <%= form.submit "New prompt", class: "submit-button" %>
            <% end %>
          </div>
        </div>
        <div class="window">
          <div class="bar">
            <i></i>
            <div>
              <p>Explanation</p>
            </div>
          </div>
          <div class="content" data-controller="prompts">
            <%= simple_form_for @prompt, url: generate_text_prompts_path, html: { data: { target: 'prompts.bugDescription' } } do |form| %>
              <%= form.text_area :answer, id: 'bug-description', class: 'bug-textarea', placeholder: 'Wait for your explanation' %>
              <%# <%= form.button :submit, class: 'submit-button' %>
            <% end %>
          </div>
        </div>
      </div>
    </ul>
  </div>

app/views/recordings/new.html.erb
<div class="d-flex justify-content-center align-items-center bg-white">
  <div class="lines"></div>
  <div class="title-wrapper px-4">
    <h1 class="text-dark text-decoration-none">Your Recording</h1>
  </div>
  <div class="lines"></div>
</div>

<div class="screen2">
  <ul class="icons2">
    <button id="record-button" class="btn-primary mt-5 ml-5" >Record</button>
    <div class="d-flex flex-column-reverse bd-highlight p-3">
      <% @recordings.each do |recording| %>
        <p class="lang-title3">Your audio recorded on: <%= recording.created_at.strftime("%A, %B %d, %Y %I:%M %p") %></p>
        <audio controls>
            <source src="<%= url_for(recording.audio) %>" type="audio/mp3">
            Your browser does not support the audio element.
        </audio>
        <br>
      <% end %>
    <div>
  </ul>
</div>

<script>
  const recordButton = document.getElementById('record-button');
  const csrfToken = document.querySelector('meta[name="csrf-token"]').content;

  // Access the user's microphone
  navigator.mediaDevices.getUserMedia({ audio: true })
    .then(function(stream) {
      const mediaRecorder = new MediaRecorder(stream);
      let chunks = [];

      // Start & Stop recording logic
      recordButton.addEventListener('click', function() {
        if (mediaRecorder.state === 'inactive') {
          mediaRecorder.start();
          recordButton.textContent = 'Stop Recording';
        } else {
          mediaRecorder.stop();
          recordButton.textContent = 'Record';
        }
      });

      // Push the blob into Array
      mediaRecorder.ondataavailable = function(e) {
        chunks.push(e.data);
      };

      // Logic to send the recorded audio to Rails RecordingsController
      mediaRecorder.onstop = function() {
        const blob = new Blob(chunks, { type: 'audio/webm' });
        const formData = new FormData();
        formData.append('recording[audio]', blob);
        formData.append('authenticity_token', csrfToken);

        fetch('/recordings', {
          method: 'POST',
          body: formData
        })
        .then(function(response) {
          if (response.ok) {
            window.location.href = 'https://www.patofix.nl/recordings/new';
          }
        })

        chunks = [];
      };
    });
</script>

app/views/tracks/show.html.erb
<div class="d-flex justify-content-center align-items-center bg-white">
  <div class="lines"></div>
  <div class="title-wrapper px-4">
    <h1 class="text-dark text-decoration-none"><%= @track.title %></h1>
  </div>
  <div class="lines"></div>
</div>
<div class="screen2">
  <ul class="icons2">
    <div class="row justify-content-center">
      <% @lessons.each do |lesson| %>
        <div class="col-6 col-md-2 mt-2">
          <%= link_to lesson_path(lesson), class: 'text-decoration-none' do %>
            <div class="square-card">
              <div class="square-card-content">
                <h5 class="text-dark text-decoration-none square-card-content"><%= lesson.title %></h5>
                <p class="text-dark text-decoration-none square-card-content">Difficulty: <%= lesson.difficulty %>/5</p>
                <%# <div class="row">
                  <div class="col-1 progress-done mx-1"></div>
                  <div class="col-1 progress-done mx-1"></div>
                  <div class="col-1 progress-done mx-1"></div>
                  <div class="col-1 progress-done mx-1"></div>
                  <div class="col-1 progress-done mx-1"></div>
                  <div class="col-1 progress-done mx-1"></div>
                  <div class="col-1 progress-done mx-1"></div>
                  <div class="col-1 progress-undone"></div>
                  <div class="col-1 progress-undone"></div>
                  <div class="col-1 progress-undone"></div>
                  <div class="col-1 progress-undone"></div>
                  <div class="col-1 progress-undone"></div>
                </div> %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="d-flex justify-content-center">
      <%= link_to language_path(@language), class: "text-dark folder-wrapper" do %>
        <strong>↵Back to tracks</strong>
      <% end %>
    </div>
  </ul>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>