config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#landing"
  get "/dashboard", to: "pages#dashboard", as: "dashboard"

  resources :languages, only: %i[index show] do
    resources :tracks, only: %i[show]
  end

  resources :recordings, only: [:new, :create]

  resources :lessons, only: %i[index show create] do
    resources :posts, only: %i[index show create]
  end

  resources :posts, only: %i[destroy] do
    resources :comments, only: %i[create destroy]
  end

  resources :comments, only: %i[destroy]

  resources :prompts, only: %i[new create show] do
    collection do
      post :generate_text
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :content, presence: true
end

app/models/hint.rb
class Hint < ActiveRecord::Base
  belongs_to :lesson

  validates :content, presence: true
  validates :lesson_id, presence: true
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :tracks, dependent: :destroy
  has_one_attached :image

  validates :name, presence: true
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :track
  has_many :started_lessons,  dependent: :destroy
  has_many :hints, dependent: :destroy
  has_many :posts, dependent: :destroy

  validates :title, presence: true
  validates :content, presence: true
  validates :track_id, presence: true
  validates :difficulty, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :lesson
  has_many :comments, dependent: :destroy

  validates :content, presence: true
  validates :title, presence: true

  default_scope -> { order(created_at: :desc) }

  def self.from_users_followed_by(user)

    followed_user_ids = "SELECT followed_id FROM relationships
                          WHERE follower_id = :user_id"
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id",
          user_id: user.id)
  end
end

app/models/prompt.rb
class Prompt < ActiveRecord::Base
  belongs_to :user

  validates :question, presence: true
end

app/models/recording.rb
class Recording < ApplicationRecord
  belongs_to :user
  has_one_attached :audio
end

app/models/started_lesson.rb
class StartedLesson < ActiveRecord::Base
  belongs_to :lesson
  belongs_to :user

  validates :lesson_id, presence: true
  validates :user_id, presence: true
  validates :staus, presence: true
end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :language
  has_many :lessons, dependent: :destroy

  validates :title, presence: true
  validates :language, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :avatar
  has_many :recordings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: { message: 'This username is already in use' }
  validates :password, presence: true

  has_many :started_lessons, dependent: :destroy
  has_many :lessons, through: :started_lessons
  has_many :tracks, through: :lessons
  has_many :posts
  has_many :comments
  has_many :prompts
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[edit update destroy]

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @comment.post = @post
    if @comment.save
      flash[:notice] = "Comment created successfully."
      redirect_to lesson_post_path(@post.lesson.id, @post)
    else
      flash[:alert] = "Comments can't be empty."
    end
  end

  def destroy
    @comment.destroy
    redirect_to lesson_post_path(@comment.post.lesson, @comment.post), notice: "Comment successfully deleted."
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @language = Language.includes(:image_attachment)
    @languages = Language.all
  end

  def show
    @language = Language.find(params[:id])
    @tracks = @language.tracks
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show]

  def show
  end

  def search
    query = params[:query]
    @lessons = Lesson.where("title LIKE ? OR content LIKE ?", "%#{query}%", "%#{query}%")
  end

  private

  def set_lesson
    @lesson = Lesson.find(params[:id])
  end

  def lesson_params
    params.require(:lesson).permit(:title, :content, :columns_explanation, :difficulty)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[landing dashboard]
  layout 'landing', only: [:landing]
  

  def landing
  end

  def dashboard
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show destroy]
  before_action :set_lesson, only: %i[index create]

  def index
    @post = Post.new
  end

  def show
    @comment = Comment.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @post.lesson = @lesson
    if @post.save
      redirect_to lesson_posts_path(@lesson)
    else
      render :index, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy
    redirect_to lesson_path(@post.lesson.id), notice: "Post successfully deleted."
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def set_lesson
    @lesson = Lesson.find(params[:lesson_id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/prompts_controller.rb
class PromptsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[show new generate_text]

  def show
    @prompt = Prompt.find(params[:id])
  end

  def new 
    @prompt = Prompt.new
  end

  def generate_text
    @prompt = Prompt.new(prompt_params)
    @prompt.user = current_user

    response = OpenaiService.new("#{prompt_params[:question]} - dont give the answer, explain me what's wrong, short concise words").call
    @prompt.answer = response

    if @prompt.save
      redirect_to prompt_path(@prompt)
    else
      render json: @prompt.errors, status: :unprocessable_entity
    end
  end
  
  private

  def prompt_params
    params.require(:prompt).permit(:question)
  end
end

app/controllers/recordings_controller.rb
class RecordingsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[new create]

  def new
      @recording = Recording.new
      @recordings = Recording.all
    end
  
    def create
      @recording = Recording.new(recording_params)
      @recording.user = current_user
      
      if @recording.save
        redirect_to root_path
      else
        render :new, status: :unprocessable_entity
      end
    end
  
    private
  
    def recording_params
      params.require(:recording).permit(:audio)
    end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  # Do we want this still?
  skip_before_action :authenticate_user!, only: [:show]

  before_action :set_language, :set_track, only: [:show]

  def show
     @lessons = @track.lessons
  end

  private

  def set_language
    @language = Language.find(params[:language_id])
  end

  def set_track
    @track = @language.tracks.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chats/index.html.erb
<h1>Chats#index</h1>
<p>Find me in app/views/chats/index.html.erb</p>

app/views/ducks/show.html.erb
<div class="d-flex justify-content-center align-items-center">
    <div class="screen2">
        <ul class="icons2">
            <h1>Ducks#show</h1>
            <p>Find me in app/views/ducks/show.html.erb</p>
        <div>
    <div>
<div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer"></div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to dashboard_path, class: "navbar-brand" do %>
      <%= image_tag("patofix-logo.svg", class: 'logo-nav') %>
      <%= image_tag("pato_fix_text.png", class: 'pato-text') %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="mt-3 me-2"> Hi, <%= current_user.username %>!</li>
          <li class="nav-item dropdown">
            <a href="#" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag("duck1ava.png", class: "avatar", alt: "dropdown menu") %>
              <%# <% if current_user.avatar.attached? %>
                <%# <%= cl_image_tag(current_user.avatar.key, class: "avatar", alt: "dropdown menu") %>
                <%# <%= image_tag("duck1ava.png", class: "avatar", alt: "dropdown menu") %> 
              <%# <% else %> 
                <%# <%= image_tag("duck1ava.png", class: "avatar-bordered", alt: "dropdown menu") %> 
              <%# <% end %>  
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", "#", class: "dropdown-item" %>
              <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
              <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <br>
          <br>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<script src="https://kit.fontawesome.com/b5d54b73c2.js" crossorigin="anonymous"></script>


<nav class="main-menu" id="sidebar-body">
  <div>
    <%= link_to("#", class: "logo") do %>
      <div class="settings"></div>
       <div class="scrollbar" id="style-1">
        <ul>
          <li class="darkerli">
            <%= link_to(dashboard_path) do %>
              <%= image_tag("dashboard.png", alt: "dashboard", class: "dashboard-img") %>
              <span class="nav-text">Dashboard</span>
            <% end %>
          </li>

          <li class="darkerli">
            <%= link_to(languages_path) do %>
              <%= image_tag("folder_img.png", alt: "lesson", class: "folder-img") %>
              <span class="nav-text">All languages</span>
            <% end %>
          </li>

          <li class="darkerli">
            <%= link_to(language_path(Language.find_by(name: 'Ruby'))) do %>
              <%= image_tag("ruby_img.png", alt: "ruby", class: "ruby-img") %>
              <span class="nav-text">Ruby</span>
            <% end %>
          </li>

          <li class="darkerli">
            <%= link_to(language_path(Language.find_by(name: 'JavaScript'))) do %>
              <%= image_tag("js_img.png", alt: "java-script", class: "js-img") %>
              <span class="nav-text">JavaScript</span>
            <% end %>
          </li>

          <li class="darkerli">
            <%= link_to(language_path(Language.find_by(name: 'HTML'))) do %>
              <%= image_tag("html_img.png", alt: "html", class: "html-img") %>
              <span class="nav-text">HTML</span>
            <% end %>
          </li>

          <li class="darkerli">
            <%= link_to(language_path(Language.find_by(name: 'CSS'))) do %>
              <%= image_tag("css_img.png", alt: "css", class: "css-img") %>
              <span class="nav-text">CSS</span>
            <% end %>
          </li>

          <li class="darkerli">
            <%= link_to (new_prompt_path) do %>
              <%= image_tag("duck_icon.png", alt: "debug", class: "duck-sidebar") %>
              <span class="nav-text">Debug</span>
            <% end %>
          </li>

          <li class="darkerli">
            <%= link_to(new_recording_path) do %>
              <%= image_tag("duckrec.png", alt: "duck", class: "duckrec-sidebar") %>
              <span class="nav-text">
              Talk to the duck
              </span>
            <% end %>
          </li>

          <li class="darkerli">
            <%= link_to lesson_posts_path(lesson_id: 27) do %>
              <i class="fa fa-comments-o fa-xl"></i>
              <span class="nav-text">Community</span>
            <% end %>
          </li>

          <li class="darkerli">
            <%= link_to("#") do %>
              <i class="fa fa-envelope-o fa-xl"></i>
              <span class="nav-text">Contact</span>
            <% end %>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
</nav>